i=6;
hold on;
plot(case1.time,case1.data(:,i));
pause(3);
plot(case2.time,case2.data(:,i));
pause(3);
plot(case3.time,case3.data(:,i));
pause(3);
plot(case4.time,case4.data(:,i));
pause(3);
plot(case5.time,case5.data(:,i));